name: backwards_compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  roave-backwards-compatibility-check:
    needs: test
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    name: Roave Backwards Compatibility Check
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event.pull_request.base.ref != 'main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set safe directory
        run: git config --global --add safe.directory /github/workspace
      - name: "Check for BC breaks"
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

          docker run --rm \
            -v "${GITHUB_WORKSPACE}":/github/workspace \
            -w /github/workspace \
            nyholm/roave-bc-check-ga